### ISSUE TITLE
Create table/doc of NWB converters & tutorials

### ISSUE THREAD

**Issue by nicolocin** [dandi/dandi.github.io#25]
@satra should I write it as a Markdown file?

**Comment by satra** [comment]
@nicolocin - transferred the issue here. you can indeed add it here in this repo. perhaps create a new page called Help and add things there.

it would be also good to move the [workflow information from here](https://docs.google.com/document/d/1ehxd5a6Hurz7VqQDAszEpGASRTUP6muXYwJ5wgXhzU4/edit) to this new page.

**Comment by yarikoptic** [comment]
I would say that having exhaustive list is probably better to have somewhere on NWB pages. In our case we refer to NeuroConv already on https://www.dandiarchive.org/handbook/13_upload/#data-uploadmanagement-workflow within that page @satra pointed to above. And given that there were no other action for years on this issue, I would just close it.
