### ISSUE TITLE
Initiate "DANDI blog"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi.github.io#38]
which IMHO could not only host "DANDI posts" but also posts from/with related to DANDI projects (nwbexplorer, DANDI contributors, etc) raising awareness of which would benefit larger DANDI user base.

**Comment by satra** [comment]
we can indeed welcome guest posts from data providers. @bendichter - are there some dandisets that you or someone from your team would want to write a short post about? may be the one from bing?

**Comment by bendichter** [comment]
Sure, we can write about the one from Bing. They are in the process of publishing a manuscript on it as well. Maybe we can embargo the post until the paper gets published.

I also think it would be nice to establish a tradition of making blog posts that explain feature releases. We could make posts for the dandi hub, for publish pipeline, and data streaming, and for the upcoming embargo feature. I'm envisioning these might look kind of like Google blog posts. It is really helpful for us when we release newsletters to have posts like this to link to, because we generally only devote a few sentences to each item in the email itself.

**Comment by satra** [comment]
initiated.
